  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: aws-auth
    namespace: kube-system
  data:
    mapRoles: |
      - rolearn: arn:aws:iam::880254308112:role/terraform-eks-demo-node
        username: system:node:{{EC2PrivateDNSName}}
        groups:
          - system:bootstrappers
          - system:nodes

      - rolearn: arn:aws:iam::880254308112:role/codebuild-eks
        username: codebuild-eks
        groups:
          - system:masters 
